version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ./caddy_config:/config
      # - /Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_TYPE: '${DB_TYPE}'
      MB_DB_DBNAME: '${DB_NAME}'
      MB_DB_FILE: '${MB_DB_FILE}'
      MB_DB_PORT: '${DB_PORT}'
      MB_DB_USER: '${DB_USER}'
      MB_DB_HOST: '${DB_HOST}'
      MB_DB_PASS: '${DB_PASSWORD}'
      JAVA_TIMEZONE: '${MB_JAVA_TIMEZONE}'
    ports:
      # <Port exposed>:<Port running inside container>
      - '${MB_PORT}:3000'
    volumes:
      # Volumes where Metabase data will be persisted
      - 'mb-data:/metabase-data'

volumes:
  mb-data:
     external: true 
  caddy_data:
    external: true 
  caddy_config:
